### ISSUE TITLE
Crashing of the app.

### ISSUE THREAD

**Issue by Marventex** [akshayub/NITKart#1]
I already have loaded items on the listview using the firebase, but still theres no images, my server is still not running. 
By clicking the addtocart button and shopping cart button it crashes.. heres the project catlog.
![addingtocart](https://user-images.githubusercontent.com/32882019/32278781-ac9d851a-bf0e-11e7-8898-ce4b5ef7537f.png)
![shoppingcart](https://user-images.githubusercontent.com/32882019/32278782-ace09c60-bf0e-11e7-802f-57283d9dc0f2.png)

**Comment by akshayub** [comment]
The above errors point towards null objects, which means they aren't existing yet.
In IndividualProduct.java, my line 150 is a comment. What changes have you made in your local version of this repo?

Have you connected the application to your instance of Firebase?
A lot of functionalities are connected to that.
